### PR TITLE
Appveyor and pkgdown

### LINKED ISSUE #147: testthat failing on windows
**Describe the bug**
testthat tests fail on windows due to annual recruitment

**To Reproduce**
Run tests on a windows machine

**Expected behavior**
...tests pass...

### PR DESCRIPTION
**Pull request by aghaynes**
appveyor tests on windows, pkgdown creates a website from readme, helpfiles and vignettes
this also closes #147

### CODE REVIEW

File: R/plot_recruitment.R [hunk 1]
```diff
@@ -102,15 +102,16 @@ plot_recruitment <- function(x, return_data = FALSE, show_centres = TRUE, cex =
...
+  # dates_centre_ids$centre_name <- dates_centre_ids$centre_id
+  dates_centre_ids$centre_name <- ctr$mnpctrname[match(dates_centre_ids$centre_id, ctr$mnpctrid)]
+  # for (i in 1:nrow(ctr)) {
+  #   curr_line <- ctr[i, ]
+  #   dates_centre_ids$centre_name <- gsub(dates_centre_ids$centre_name,
+  #                                        # force full length match with "^ $" to avoid substring match
+  #                                        pattern = paste0("^", curr_line$mnpctrid, "$"),
+  #                                        replacement = curr_line$mnpctrname,
+  #                                        useBytes = TRUE)
+  # }
```
Comment (PatrickRWright) [inline R/plot_recruitment.R]: Feel free to remove the old code.

**Comment by PatrickRWright** [comment]
Thanks @aghaynes I suggest we wait until travis is back to working until I merge.

Out of interest: Could you add the links to the resources you used to get this set up to your PR comment please?

**Comment by aghaynes** [comment]
Here's some links
appveyor : https://usethis.r-lib.org/reference/ci.html (as simple as `usethis::use_appveyor()`, which adds the relevant stuff to `.Rbuildignore` and the relevant settings)
pkgdown : https://pkgdown.r-lib.org/ (as simple as `pkgdown::build_site`, which creates the HTML, `usethis::use_pkgdown()` adds the relevant parts to `.Rbuildignore`)
